org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.22
forge_version_range=[47,48)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1
mod_id=metatech_reborn
mod_name=MetaTech Reborn
mod_license=MIT
mod_version=0.6.68-full-sync
mod_group_id=ru.rfvv.metatechreborn
mod_authors=rfvv
mod_description=Forge 1.20.1 full source sync: 81-slot Mana Drill and luck converters, stacked greenhouse flowers, four greenhouse module slots, infinite water/lava modules, ghost 9x9 pattern encoding, Re-Avaritia crafting modes, AE2 Overclocked Super Speed Card support, refreshed GUIs and aligned textures.
